/* #undef HAVE_PRAGMA_OMP_SIMD */

/* #undef MATRIXLIB_BRAINCORPS_VER_MAJOR */
/* #undef MATRIXLIB_BRAINCORPS_VER_MINOR */
#define MATRIXLIB_BRAINCORPS_VER_PATCH 1
#define MATRIXLIB_BRAINCORPS_VERSION "0.0.1"
